name: Code Quality
on:
  - push
jobs:
  fmt:
    name: QA IntelliJ Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: telenornorway/setup-intellij@v0.1.0
      - uses: telenornorway/action-intellij-format@v0.1.13
  lint:
    name: QA IntelliJ Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: telenornorway/setup-intellij@v0.1.0
      - uses: telenornorway/action-intellij-inspect@v0.1.11
  cq:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: github/codeql-action/init@v2
        with:
          languages: java
      - run: ./gradlew build
      - uses: github/codeql-action/analyze@v2
        with:
          category: /language:java
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew test
